dd if= bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/.gz
dd if=/dev/block/mmcblk0p15 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/DDR.gz
dd if=/dev/block/mmcblk0p19 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/aboot.gz
dd if=/dev/block/mmcblk0p20 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/abootbak.gz
dd if=/dev/block/mmcblk0p45 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/apdp.gz
dd if=/dev/block/mmcblk0p21 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/boot.gz
dd if=/dev/block/mmcblk0p25 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/cache.gz
dd if=/dev/block/mmcblk0p39 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/cmnlib.gz
dd if=/dev/block/mmcblk0p41 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/cmnlib64.gz
dd if=/dev/block/mmcblk0p42 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/cmnlib64bak.gz
dd if=/dev/block/mmcblk0p40 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/cmnlibbak.gz
dd if=/dev/block/mmcblk0p29 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/config.gz
dd if=/dev/block/mmcblk0p48 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/cust.gz
dd if=/dev/block/mmcblk0p10 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/devcfg.gz
dd if=/dev/block/mmcblk0p11 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/devcfgbak.gz
dd if=/dev/block/mmcblk0p23 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/devinfo.gz
dd if=/dev/block/mmcblk0p33 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/dip.gz
dd if=/dev/block/mmcblk0p47 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/dpo.gz
dd if=/dev/block/mmcblk0p12 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/dsp.gz
dd if=/dev/block/mmcblk0p2 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/fsc.gz
dd if=/dev/block/mmcblk0p16 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/fsg.gz
dd if=/dev/block/mmcblk0p43 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/keymaster.gz
dd if=/dev/block/mmcblk0p44 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/keymasterbak.gz
dd if=/dev/block/mmcblk0p28 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/keystore.gz
dd if=/dev/block/mmcblk0p31 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/limits.gz
dd if=/dev/block/mmcblk0p37 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/lksecapp.gz
dd if=/dev/block/mmcblk0p38 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/lksecappbak.gz
dd if=/dev/block/mmcblk0p36 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/mcfg.gz
dd if=/dev/block/mmcblk0p34 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/mdtp.gz
dd if=/dev/block/mmcblk0p27 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/misc.gz
dd if=/dev/block/mmcblk0p1 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/modem.gz
dd if=/dev/block/mmcblk0p13 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/modemst1.gz
dd if=/dev/block/mmcblk0p14 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/modemst2.gz
dd if=/dev/block/mmcblk0p32 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/mota.gz
dd if=/dev/block/mmcblk0p46 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/msadp.gz
dd if=/dev/block/mmcblk0p30 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/oem.gz
dd if=/dev/block/mmcblk0p26 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/persist.gz
dd if=/dev/block/mmcblk0p22 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/recovery.gz
dd if=/dev/block/mmcblk0p6 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/rpm.gz
dd if=/dev/block/mmcblk0p7 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/rpmbak.gz
dd if=/dev/block/mmcblk0p4 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/sbl1.gz
dd if=/dev/block/mmcblk0p5 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/sbl1bak.gz
dd if=/dev/block/mmcblk0p17 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/sec.gz
dd if=/dev/block/mmcblk0p18 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/splash.gz
dd if=/dev/block/mmcblk0p3 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/ssd.gz
dd if=/dev/block/mmcblk0p35 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/syscfg.gz
#  dd if=/dev/block/mmcblk0p24 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/system.gz
dd if=/dev/block/mmcblk0p8 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/tz.gz
dd if=/dev/block/mmcblk0p9 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/tzbak.gz
#  dd if=/dev/block/mmcblk0p49 bs=4096 | gzip > /storage/C0DE-BA5E/Backups/Partitions/userdata.gz
