#!/system/bin/sh
if [ ! -e /data/jpchil/batchBackup ]; then mkdir /data/jpchil/batchBackup; fi
/data/jpchil/jAndBackup/jAndBackup I > /data/jpchil/log/jAndBackup.log 2>&1
find /sdcard/jBackup/ -mtime -1 | wc -l > /sdcard/log/jAndBackup.count
