#!/system/bin/sh
if [ ! -e /sdcard/jAndBackup ]; then mkdir /sdcard/jAndBackup; fi
/data/jpchil/jAndBackup/jAndBackup I > /sdcard/log/jAndBackup.log 2>&1
find /sdcard/jAndBackup/ -mtime -1 | wc -l > /sdcard/log/jAndBackup.count
