#!/system/xbin/ash
#
# 20190205 /jps - restore jAndBackups
# 20191005 /jps - install apk for user who needs it and not all
#

BackDir="/sdcard/jBackup/"

# restore user data and apk for user
for AppTar in $(find $BackDir -type f -iname "*-User*.tgz"); do
  Package=$(echo $AppTar | sed -n 's/.*\/\(.*\)-User.*.tgz/\1/p')
  if  [ "$Package" == "" ]; then             
    echo "Error- unerwartetes Format $AppTar"
  else                       
    User=$(echo $AppTar | sed -n 's/.*-User\(.*\)\.tgz/\1/p')             
    echo "Restoring $Package data for User $User"
    tar -xzf $AppTar -C /                                    
    PUid=$(cmd package list packages -U $Package | awk -v User=${User} -F: '{ print "u"User"_"$3 }' | sed 's/1.0/a/g')
    chown -R $PUid:$PUid /data/user*/$User/*$Package*
    ApkTar=$BackDir$Package-apk.tgz
    if [ ! -e $ApkTar ]; then 
      echo "Error - no $ApkTar found"
    else
      if [ $Package = "net.typeblog.shelter" ] && [ $User != 0 ]; then                                                                                                                                                               
        echo "Will not install apk for $Package for $User"
      else
        echo "Restoring apk for $Package and user $User"
        tar -xzf $ApkTar -C /
        # only one version of the same packagename - I dont know better
        InstallApk=$(find /data/app/*$Package*/ -name base.apk | tail -1)
        pm install --user $User $InstallApk
      fi
    fi
  fi

done
