#!/system/xbin/ash
#
# 20190205 /jps - restore jAndBackups
#

BackDir="/storage/C0DE-BA5E/Backups/jBackup"

if [ "$1" == "" ]; then echo "Package name missing "; exit; fi
ApkTar=$(find $BackDir/*$1*apk.tgz | tail -1)
Package=$(echo $ApkTar | sed 's/.*\/\(.*\)-apk.tgz/\1/')
if [ "$Package" == "" ]; then echo "Package $Package not found"; exit; fi
printf "Restore $ApkTar (Y/N)"
read YesNo
Answer=$(echo $YesNo | tr '[:lower:]' '[:upper:]')
if [ "$Answer" != "Y" ]; then exit; fi
                                      
# restore apk                         
tar -vxzpf $ApkTar -C /               
find /data/app/$Package*/ -name base.apk -exec pm install {} \;
                                                               
# restore data                                                 
find $BackDir/$Package*User*.tgz -exec tar -vxzpf {} -C / \;   
PUid=$(cmd package list packages -U $Package | awk -v User=${User} -F: '{ print $3 }')
chown -R $PUid:$PUid /data/user*/*/$Package